// ÜRETİLMİŞ DOSYA — ELLE DÜZENLEME.
//
// Kaynak: src/landing/demoBoard.ts (`DEMO_TILES_2` + `DEMO_TILES_4`)
// Yeniden üret: npm run generate-demo-board-dart
//
// Web'in karşılama katmanındaki 2 ve 4 kişilik tanıtım tahtaları. Her yatay/dikey
// dizilimin gerçek bir Türkçe kelime olduğu ve izole hamlelerin gerçekten
// izole kaldığı `npm run verify-demo-board` ile ÖLÇÜLEREK doğrulanıyor —
// bu dosya o doğrulanmış kaynaktan üretildiği için ayrıca sınanmıyor.
import 'package:kelimeki_core/kelimeki_core.dart';

const List<BoardSnapshotTile> kDemoTiles2 = [
  BoardSnapshotTile(r: 0, c: 0, l: 'K', o: 0),
  BoardSnapshotTile(r: 0, c: 1, l: 'E', o: 0),
  BoardSnapshotTile(r: 0, c: 2, l: 'L', o: 0),
  BoardSnapshotTile(r: 0, c: 3, l: 'İ', o: 0),
  BoardSnapshotTile(r: 0, c: 4, l: 'M', o: 0),
  BoardSnapshotTile(r: 0, c: 5, l: 'E', o: 0),
  BoardSnapshotTile(r: 1, c: 0, l: 'A', o: 0),
  BoardSnapshotTile(r: 2, c: 0, l: 'P', o: 0),
  BoardSnapshotTile(r: 3, c: 0, l: 'I', o: 0),
  BoardSnapshotTile(r: 3, c: 1, l: 'R', o: 0),
  BoardSnapshotTile(r: 3, c: 2, l: 'M', o: 0),
  BoardSnapshotTile(r: 3, c: 3, l: 'A', o: 0),
  BoardSnapshotTile(r: 3, c: 4, l: 'K', o: 0),
  BoardSnapshotTile(r: 4, c: 2, l: 'A', o: 0),
  BoardSnapshotTile(r: 5, c: 2, l: 'S', o: 0),
  BoardSnapshotTile(r: 6, c: 2, l: 'A', o: 0),
  BoardSnapshotTile(r: 7, c: 2, l: 'L', o: 0),
  BoardSnapshotTile(r: 4, c: 4, l: 'U', o: 0),
  BoardSnapshotTile(r: 5, c: 4, l: 'Z', o: 0),
  BoardSnapshotTile(r: 6, c: 4, l: 'E', o: 0),
  BoardSnapshotTile(r: 7, c: 4, l: 'Y', o: 0),
  BoardSnapshotTile(r: 7, c: 0, l: 'K', o: 0),
  BoardSnapshotTile(r: 7, c: 1, l: 'O', o: 0),
  BoardSnapshotTile(r: 7, c: 3, l: 'A', o: 0),
  BoardSnapshotTile(r: 5, c: 5, l: 'A', o: 0),
  BoardSnapshotTile(r: 5, c: 6, l: 'M', o: 0),
  BoardSnapshotTile(r: 5, c: 7, l: 'A', o: 0),
  BoardSnapshotTile(r: 5, c: 8, l: 'N', o: 0),
  BoardSnapshotTile(r: 6, c: 8, l: 'E', o: 0),
  BoardSnapshotTile(r: 7, c: 8, l: 'D', o: 0),
  BoardSnapshotTile(r: 8, c: 8, l: 'E', o: 0),
  BoardSnapshotTile(r: 9, c: 8, l: 'N', o: 0),
  BoardSnapshotTile(r: 9, c: 9, l: 'A', o: 0),
  BoardSnapshotTile(r: 9, c: 10, l: 'İ', o: 0),
  BoardSnapshotTile(r: 9, c: 11, l: 'L', o: 0),
  BoardSnapshotTile(r: 12, c: 9, l: 'O', o: 1),
  BoardSnapshotTile(r: 12, c: 10, l: 'Y', o: 1),
  BoardSnapshotTile(r: 12, c: 11, l: 'U', o: 1),
  BoardSnapshotTile(r: 12, c: 12, l: 'N', o: 1),
  BoardSnapshotTile(r: 10, c: 12, l: 'S', o: 1),
  BoardSnapshotTile(r: 11, c: 12, l: 'O', o: 1),
  BoardSnapshotTile(r: 10, c: 10, l: 'S', o: 1),
  BoardSnapshotTile(r: 10, c: 11, l: 'E', o: 1),
  BoardSnapshotTile(r: 1, c: 1, l: 'R', o: 1),
  BoardSnapshotTile(r: 1, c: 2, l: 'A', o: 1),
  BoardSnapshotTile(r: 1, c: 5, l: 'F', o: 1),
  BoardSnapshotTile(r: 2, c: 5, l: 'E', o: 1),
  BoardSnapshotTile(r: 8, c: 0, l: 'A', o: 1),
  BoardSnapshotTile(r: 9, c: 0, l: 'R', o: 1),
  BoardSnapshotTile(r: 11, c: 7, l: 'K', o: 0),
  BoardSnapshotTile(r: 11, c: 8, l: 'O', o: 0),
  BoardSnapshotTile(r: 11, c: 9, l: 'D', o: 0),
];

const List<BoardSnapshotTile> kDemoTiles4 = [
  BoardSnapshotTile(r: 0, c: 0, l: 'K', o: 0),
  BoardSnapshotTile(r: 0, c: 1, l: 'E', o: 0),
  BoardSnapshotTile(r: 0, c: 2, l: 'L', o: 0),
  BoardSnapshotTile(r: 0, c: 3, l: 'İ', o: 0),
  BoardSnapshotTile(r: 0, c: 4, l: 'M', o: 0),
  BoardSnapshotTile(r: 0, c: 5, l: 'E', o: 0),
  BoardSnapshotTile(r: 1, c: 0, l: 'A', o: 0),
  BoardSnapshotTile(r: 2, c: 0, l: 'P', o: 0),
  BoardSnapshotTile(r: 3, c: 0, l: 'I', o: 0),
  BoardSnapshotTile(r: 3, c: 1, l: 'R', o: 0),
  BoardSnapshotTile(r: 3, c: 2, l: 'M', o: 0),
  BoardSnapshotTile(r: 3, c: 3, l: 'A', o: 0),
  BoardSnapshotTile(r: 3, c: 4, l: 'K', o: 0),
  BoardSnapshotTile(r: 4, c: 4, l: 'U', o: 0),
  BoardSnapshotTile(r: 5, c: 4, l: 'Z', o: 0),
  BoardSnapshotTile(r: 6, c: 4, l: 'E', o: 0),
  BoardSnapshotTile(r: 7, c: 4, l: 'Y', o: 0),
  BoardSnapshotTile(r: 5, c: 5, l: 'A', o: 0),
  BoardSnapshotTile(r: 5, c: 6, l: 'M', o: 0),
  BoardSnapshotTile(r: 5, c: 7, l: 'A', o: 0),
  BoardSnapshotTile(r: 5, c: 8, l: 'N', o: 0),
  BoardSnapshotTile(r: 0, c: 7, l: 'B', o: 1),
  BoardSnapshotTile(r: 0, c: 8, l: 'A', o: 1),
  BoardSnapshotTile(r: 0, c: 9, l: 'L', o: 1),
  BoardSnapshotTile(r: 0, c: 10, l: 'K', o: 1),
  BoardSnapshotTile(r: 0, c: 11, l: 'O', o: 1),
  BoardSnapshotTile(r: 0, c: 12, l: 'N', o: 1),
  BoardSnapshotTile(r: 1, c: 12, l: 'A', o: 1),
  BoardSnapshotTile(r: 2, c: 12, l: 'R', o: 1),
  BoardSnapshotTile(r: 2, c: 10, l: 'S', o: 1),
  BoardSnapshotTile(r: 2, c: 11, l: 'I', o: 1),
  BoardSnapshotTile(r: 3, c: 10, l: 'A', o: 1),
  BoardSnapshotTile(r: 4, c: 10, l: 'P', o: 1),
  BoardSnapshotTile(r: 1, c: 8, l: 'T', o: 1),
  BoardSnapshotTile(r: 2, c: 8, l: 'A', o: 1),
  BoardSnapshotTile(r: 3, c: 8, l: 'M', o: 1),
  BoardSnapshotTile(r: 4, c: 8, l: 'A', o: 1),
  BoardSnapshotTile(r: 12, c: 0, l: 'K', o: 2),
  BoardSnapshotTile(r: 12, c: 1, l: 'U', o: 2),
  BoardSnapshotTile(r: 12, c: 2, l: 'Z', o: 2),
  BoardSnapshotTile(r: 12, c: 3, l: 'E', o: 2),
  BoardSnapshotTile(r: 12, c: 4, l: 'Y', o: 2),
  BoardSnapshotTile(r: 11, c: 0, l: 'O', o: 2),
  BoardSnapshotTile(r: 11, c: 4, l: 'A', o: 2),
  BoardSnapshotTile(r: 11, c: 5, l: 'D', o: 2),
  BoardSnapshotTile(r: 11, c: 6, l: 'A', o: 2),
  BoardSnapshotTile(r: 11, c: 7, l: 'M', o: 2),
  BoardSnapshotTile(r: 8, c: 7, l: 'K', o: 2),
  BoardSnapshotTile(r: 9, c: 7, l: 'R', o: 2),
  BoardSnapshotTile(r: 10, c: 7, l: 'E', o: 2),
  BoardSnapshotTile(r: 12, c: 9, l: 'O', o: 3),
  BoardSnapshotTile(r: 12, c: 10, l: 'Y', o: 3),
  BoardSnapshotTile(r: 12, c: 11, l: 'U', o: 3),
  BoardSnapshotTile(r: 12, c: 12, l: 'N', o: 3),
  BoardSnapshotTile(r: 10, c: 12, l: 'S', o: 3),
  BoardSnapshotTile(r: 11, c: 12, l: 'O', o: 3),
  BoardSnapshotTile(r: 10, c: 10, l: 'S', o: 3),
  BoardSnapshotTile(r: 10, c: 11, l: 'E', o: 3),
  BoardSnapshotTile(r: 8, c: 10, l: 'K', o: 3),
  BoardSnapshotTile(r: 9, c: 10, l: 'A', o: 3),
  BoardSnapshotTile(r: 8, c: 8, l: 'I', o: 3),
  BoardSnapshotTile(r: 8, c: 9, l: 'R', o: 3),
  BoardSnapshotTile(r: 1, c: 1, l: 'R', o: 3),
  BoardSnapshotTile(r: 1, c: 2, l: 'A', o: 3),
  BoardSnapshotTile(r: 3, c: 12, l: 'İ', o: 2),
  BoardSnapshotTile(r: 4, c: 12, l: 'N', o: 2),
  BoardSnapshotTile(r: 8, c: 0, l: 'P', o: 1),
  BoardSnapshotTile(r: 9, c: 0, l: 'A', o: 1),
  BoardSnapshotTile(r: 10, c: 0, l: 'D', o: 1),
  BoardSnapshotTile(r: 9, c: 11, l: 'N', o: 0),
];
